//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardProcessing
    {
        public int CP_ID { get; set; }
        public Nullable<int> InvoiceID { get; set; }
        public Nullable<decimal> PF { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> InvoiceAmount { get; set; }
    
        public virtual InvoiceInfo InvoiceInfo { get; set; }
    }
}
