//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chart
    {
        public string M { get; set; }
        public string MName { get; set; }
        public string T { get; set; }
        public string TName { get; set; }
        public string AccountNo { get; set; }
        public string AccountName { get; set; }
        public Nullable<System.DateTime> OpenDate { get; set; }
        public Nullable<double> OpeningBalance { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string FaxNo { get; set; }
        public string GstNo { get; set; }
        public string Ntn { get; set; }
    }
}
