//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.StockTransfers = new HashSet<StockTransfer>();
        }
    
        public int Id { get; set; }
        public string CompanyName { get; set; }
        public string MailingName { get; set; }
        public string Country { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PinCode { get; set; }
        public string ContactNo { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string TIN { get; set; }
        public string LicenseNo { get; set; }
        public string ServiceTaxNo { get; set; }
        public string CST { get; set; }
        public string PAN { get; set; }
        public string CurrencyCode { get; set; }
        public string Currency { get; set; }
        public byte[] Logo { get; set; }
        public string ShowLogo { get; set; }
        public Nullable<decimal> CapitalAccount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockTransfer> StockTransfers { get; set; }
    }
}
