//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditCustomerPayment
    {
        public int T_ID { get; set; }
        public string TransactionID { get; set; }
        public System.DateTime Date { get; set; }
        public string PaymentMode { get; set; }
        public int CreditCustomer_ID { get; set; }
        public decimal Amount { get; set; }
        public string Remarks { get; set; }
        public string PaymentModeDetails { get; set; }
    
        public virtual CreditCustomer CreditCustomer { get; set; }
    }
}
