//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditCustomerLedger
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string LedgerNo { get; set; }
        public string Label { get; set; }
        public Nullable<decimal> Debit { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public Nullable<int> CreditCustomer_ID { get; set; }
    
        public virtual CreditCustomer CreditCustomer { get; set; }
    }
}
