//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerMaster
    {
        public int Cid { get; set; }
        public string CName { get; set; }
        public string ContactNo { get; set; }
        public string RS { get; set; }
        public string RC { get; set; }
        public string RAx { get; set; }
        public string RAd { get; set; }
        public string RI { get; set; }
        public string LS { get; set; }
        public string LC { get; set; }
        public string LAx { get; set; }
        public string LAd { get; set; }
        public string LI { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> RegisteredDate { get; set; }
        public string Active { get; set; }
    }
}
