//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class FundDeposit
    {
        public int Id { get; set; }
        public string DepositerName { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string AccNo { get; set; }
        public string Notes { get; set; }
    
        public virtual BankAccountRegistration BankAccountRegistration { get; set; }
    }
}
