//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class POS_HoldBill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public POS_HoldBill()
        {
            this.POS_HoldBillItems = new HashSet<POS_HoldBillItems>();
        }
    
        public string Hold_ID { get; set; }
        public Nullable<int> OpenID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> DiscPer { get; set; }
        public Nullable<decimal> DiscAmt { get; set; }
    
        public virtual POS_OpeningCash POS_OpeningCash { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POS_HoldBillItems> POS_HoldBillItems { get; set; }
    }
}
