//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class POS_OpeningCash
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public POS_OpeningCash()
        {
            this.InvoiceInfoes = new HashSet<InvoiceInfo>();
            this.POS_ClosingCash = new HashSet<POS_ClosingCash>();
            this.POS_HoldBill = new HashSet<POS_HoldBill>();
        }
    
        public int OpenID { get; set; }
        public string TillDetails { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> OpeningDate { get; set; }
        public Nullable<decimal> OpeningCash { get; set; }
        public Nullable<int> Closed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceInfo> InvoiceInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POS_ClosingCash> POS_ClosingCash { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POS_HoldBill> POS_HoldBill { get; set; }
        public virtual Registration Registration { get; set; }
    }
}
