//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class POS_HoldBillItems
    {
        public int HBI_ID { get; set; }
        public string HoldID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string Barcode { get; set; }
        public string MfgDate { get; set; }
        public string ExpiryDate { get; set; }
        public Nullable<decimal> SalesRate { get; set; }
        public Nullable<decimal> DiscountPer { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> VATPer { get; set; }
        public Nullable<decimal> VAT { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> PurchaseRate { get; set; }
        public Nullable<decimal> Margin { get; set; }
        public Nullable<decimal> MarginPer { get; set; }
    
        public virtual POS_HoldBill POS_HoldBill { get; set; }
        public virtual Product Product { get; set; }
    }
}
