//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class POS_ClosingCash
    {
        public int ClosingID { get; set; }
        public int OpenID { get; set; }
        public Nullable<System.DateTime> ClosingDate { get; set; }
        public Nullable<decimal> ClosingBalance { get; set; }
    
        public virtual POS_OpeningCash POS_OpeningCash { get; set; }
    }
}
