//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Invoice_Product = new HashSet<Invoice_Product>();
            this.POS_HoldBillItems = new HashSet<POS_HoldBillItems>();
            this.Product_OpeningStock = new HashSet<Product_OpeningStock>();
            this.ProductLocations = new HashSet<ProductLocation>();
            this.Purchase_Join = new HashSet<Purchase_Join>();
            this.PurchaseOrder_Join = new HashSet<PurchaseOrder_Join>();
            this.PurchaseReturn_Join = new HashSet<PurchaseReturn_Join>();
            this.Sales_Product = new HashSet<Sales_Product>();
            this.SalesReturn_Join = new HashSet<SalesReturn_Join>();
            this.StockAdjustment_Store = new HashSet<StockAdjustment_Store>();
            this.StockAdjustment_Warehouse = new HashSet<StockAdjustment_Warehouse>();
            this.StockTransfer_Join_W2W = new HashSet<StockTransfer_Join_W2W>();
            this.StockTransfer_Join = new HashSet<StockTransfer_Join>();
            this.Temp_Stock = new HashSet<Temp_Stock>();
            this.Temp_Stock_Company = new HashSet<Temp_Stock_Company>();
        }
    
        public int PID { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string Alias { get; set; }
        public string VATCommodity { get; set; }
        public string Description { get; set; }
        public string Barcode { get; set; }
        public string Category { get; set; }
        public string PurchaseUnit { get; set; }
        public string SalesUnit { get; set; }
        public Nullable<decimal> PurchaseCost { get; set; }
        public Nullable<decimal> SalesCost { get; set; }
        public Nullable<int> ReorderPoint { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<decimal> MarginPer { get; set; }
    
        public virtual Category Category1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice_Product> Invoice_Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POS_HoldBillItems> POS_HoldBillItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_OpeningStock> Product_OpeningStock { get; set; }
        public virtual TaxMaster TaxMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductLocation> ProductLocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase_Join> Purchase_Join { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrder_Join> PurchaseOrder_Join { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseReturn_Join> PurchaseReturn_Join { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sales_Product> Sales_Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesReturn_Join> SalesReturn_Join { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockAdjustment_Store> StockAdjustment_Store { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockAdjustment_Warehouse> StockAdjustment_Warehouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockTransfer_Join_W2W> StockTransfer_Join_W2W { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockTransfer_Join> StockTransfer_Join { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_Stock> Temp_Stock { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_Stock_Company> Temp_Stock_Company { get; set; }
    }
}
