//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductLocation
    {
        public int ID { get; set; }
        public string RackNo { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string ShelfPosition { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Racking Racking { get; set; }
    }
}
