//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_OpeningStock
    {
        public int PS_ID { get; set; }
        public int ProductID { get; set; }
        public string StorageType { get; set; }
        public string Warehouse_Store { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public string ExpiryDate { get; set; }
        public string ManufacturingDate { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
