//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseReturn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchaseReturn()
        {
            this.PurchaseReturn_Join = new HashSet<PurchaseReturn_Join>();
        }
    
        public int PR_ID { get; set; }
        public string PRNo { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> PurchaseID { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> DiscPer { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> VATPer { get; set; }
        public Nullable<decimal> VATAmt { get; set; }
        public Nullable<decimal> FreightCharges { get; set; }
        public Nullable<decimal> OtherCharges { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> RoundOff { get; set; }
        public Nullable<decimal> GrandTotal { get; set; }
    
        public virtual Purchase Purchase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseReturn_Join> PurchaseReturn_Join { get; set; }
    }
}
