//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchaseOrder()
        {
            this.PurchaseOrder_Join = new HashSet<PurchaseOrder_Join>();
        }
    
        public int PO_ID { get; set; }
        public string PONumber { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Supplier_ID { get; set; }
        public string Terms { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> VATPer { get; set; }
        public Nullable<decimal> VATAmount { get; set; }
        public Nullable<decimal> GrandTotal { get; set; }
        public string TaxType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrder_Join> PurchaseOrder_Join { get; set; }
    }
}
