//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrder_Join
    {
        public int POJ_ID { get; set; }
        public int PurchaseOrderID { get; set; }
        public int ProductID { get; set; }
        public decimal Qty { get; set; }
        public Nullable<decimal> PricePerUnit { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual PurchaseOrder PurchaseOrder { get; set; }
    }
}
