//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesReturn_Join
    {
        public int SRJ_ID { get; set; }
        public int SalesReturnID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string Barcode { get; set; }
        public string ManufacturingDate { get; set; }
        public string ExpiryDate { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> SalesCost { get; set; }
        public Nullable<decimal> DiscPer { get; set; }
        public Nullable<decimal> DiscAmt { get; set; }
        public Nullable<decimal> CGSTPer { get; set; }
        public Nullable<decimal> CGSTAmt { get; set; }
        public Nullable<decimal> ReturnQty { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual SalesReturn SalesReturn { get; set; }
    }
}
