//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sale()
        {
            this.Sales_Product = new HashSet<Sales_Product>();
        }
    
        public int SalesID { get; set; }
        public string BillNo { get; set; }
        public System.DateTime BillDate { get; set; }
        public System.DateTime BillShamsiDate { get; set; }
        public string RefNo1 { get; set; }
        public string RefNo2 { get; set; }
        public string SalesType { get; set; }
        public string UserOperator { get; set; }
        public int PartyID { get; set; }
        public decimal SubTotal { get; set; }
        public decimal DiscountPer { get; set; }
        public decimal Discount { get; set; }
        public decimal FreightCharges { get; set; }
        public decimal OtherCharges { get; set; }
        public decimal PreviousDue { get; set; }
        public decimal Total { get; set; }
        public decimal RoundOff { get; set; }
        public decimal GrandTotal { get; set; }
        public decimal TotalPaid { get; set; }
        public decimal Balance { get; set; }
        public string Remarks { get; set; }
    
        public virtual Party Party { get; set; }
        public virtual Registration Registration { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sales_Product> Sales_Product { get; set; }
    }
}
