//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesMan
    {
        public int SM_ID { get; set; }
        public string SalesMan_ID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string ContactNo { get; set; }
        public string EmailID { get; set; }
        public string Remarks { get; set; }
        public byte[] Photo { get; set; }
        public Nullable<decimal> CommissionPer { get; set; }
    }
}
