//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesReturn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalesReturn()
        {
            this.SalesReturn_Join = new HashSet<SalesReturn_Join>();
        }
    
        public int SR_ID { get; set; }
        public string SRNo { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> SalesID { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> VAT { get; set; }
        public Nullable<decimal> GrandTotal { get; set; }
    
        public virtual InvoiceInfo InvoiceInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesReturn_Join> SalesReturn_Join { get; set; }
    }
}
