//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salesman_Commission
    {
        public int ID { get; set; }
        public int InvoiceID { get; set; }
        public decimal CommissionPer { get; set; }
        public decimal Commission { get; set; }
    
        public virtual InvoiceInfo InvoiceInfo { get; set; }
    }
}
