//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockAdjustment_Warehouse
    {
        public int SA_ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Warehouse { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string Barcode { get; set; }
        public string AdjustmentType { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public string Reason { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Warehouse Warehouse1 { get; set; }
    }
}
