//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockTransfer_W2W
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StockTransfer_W2W()
        {
            this.StockTransfer_Join_W2W = new HashSet<StockTransfer_Join_W2W>();
        }
    
        public int ST_ID { get; set; }
        public string TransferID { get; set; }
        public System.DateTime Date { get; set; }
        public string Warehouse { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockTransfer_Join_W2W> StockTransfer_Join_W2W { get; set; }
        public virtual Warehouse Warehouse1 { get; set; }
    }
}
